<a href="https://colab.research.google.com/github/kaiju-no-9/Pytorch-Notes-/blob/main/fund_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensors

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cpu


In [ ]:
#scalr
scalar = torch.tensor(7)
scalar


tensor(7)

In [ ]:
vector = torch.tensor([7,7])
vector
print(vector.ndim)
print(vector.shape)

1
torch.Size([2])


In [ ]:
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX
print(MATRIX.ndim)
print(MATRIX.shape)

2
torch.Size([2, 2])


In [ ]:
# Tesors
TENSORS= torch.tensor([[[1,2,3],[2,3,4],[4,5,6]]])
TENSORS
print(TENSORS.ndim)
print(TENSORS.shape)
print(TENSORS[0,0,0])

3
torch.Size([1, 3, 3])
tensor(1)


In [ ]:
# randrom
# they are imp bracuse a neutra network starts with a
# random set of numbers which the models work on to update
random_tansor = torch.rand(3,4)
random_tansor

tensor([[0.3324, 0.6989, 0.9667, 0.2474],
        [0.7787, 0.5311, 0.9450, 0.6848],
        [0.4138, 0.6006, 0.5787, 0.1377]])

In [ ]:
random_imagesize= torch.rand(size=(3,224,224))
random_imagesize.ndim , random_imagesize.shape

(3, torch.Size([3, 224, 224]))

In [ ]:
# tesors witj 0 and 1
zeros = torch.zeros(size=(3,4))
zeros
# once tenssor
once = torch.ones(size=(3,4))
once

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
#range(use arange ) start, stop , step
one_to_ten=torch.arange(1,11)


In [ ]:
#creating tensor likes
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#float tensor datatype
float_32_tensor= torch.tensor([2.0,1.0, 9.0] , dtype=None , device=None , requires_grad=False)
float_32_tensor
#

tensor([2., 1., 9.])

the issue you are goingto face -> (Not always)
1. tesor not right datatype   (tensor.dtype)
2. Tesor not right  shape  (tensor.shape)
3. Tesor not on right device  (tensor.device)


In [ ]:
int_32_tensor =torch.tensor([3,6,9] , dtype= torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
#Tensor manuplation(add, sub ,multi(elemnet) , div , matrix mutiplication )
tensor = torch.tensor([1,2,3])
tensor+10
tensor*10


tensor([10, 20, 30])

In [ ]:
# Matrix multiplication
print(tensor * tensor )

tensor([1, 4, 9])


 .reshapping refers to reshaping tensors

 .stacking refers to.      .stacking one tensor over the other

 .permute- return view of the input with dimention


In [12]:
x= torch.arange(1,10)
x, x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [24]:
# reshape works in the format of factor so for s matrix of
# 10 we can do (5,2) or (2,5) as the reult isthe multiple is 10
x_reshaped= x.reshape(1,10)
x_reshaped


tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [16]:
#same as reshape the diffrence is that it shares
# shape from the orignal input
z = x.view(2,5)
z, z.shape

(tensor([[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]),
 torch.Size([2, 5]))

In [18]:
#Stack function in torch
x_stacked = torch.stack([x,x,x] , dim =0)
x_stacked

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [25]:
print(f" prev :{x} ")
print(f"newShape: {x_reshaped} , {x_reshaped.shape}")
x_squeeeze = x_reshaped.squeeze()
print(f"squeezed: {x_squeeeze} , {x_squeeeze.shape}")


 prev :tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]) 
newShape: tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]) , torch.Size([1, 10])
squeezed: tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]) , torch.Size([10])


In [27]:
# addes a single tensor at a specific dim
print(f"previous targert : {x_squeeeze} ")
x_unsqueezed= x_squeeeze.unsqueeze(dim=0)
print(f"new targert : {x_unsqueezed} , {x_unsqueezed.shape} ")


previous targert : tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]) 
new targert : tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]) , torch.Size([1, 10]) 


In [31]:
# trouch.permute. rerrange the value of tensor in specific order
x_original= torch.rand(size=(224,224,5))
# we have tenssor dimmintion for [height, width, colour_channels]

# permute for origanal tensor to rearracvnge the axis (or dim ) order
x_permuted= x_original.permute(2,0,1)
print(f"previous:{x_original.shape}")
print(f"new:{x_permuted.shape}")

previous:torch.Size([224, 224, 5])
new:torch.Size([5, 224, 224])


In [39]:
x_original[0,0,0]

tensor(7332.)

In [38]:
x_permuted[0,0,0]

tensor(7332.)

Working around with indexing

In [45]:
x_index= torch.arange(1,10).reshape(1,3,3)
x_index[0][2][1]

tensor(8)

Concerting data fro numpy --to--> tensor

In [47]:
array = np.arange(1 , 8)
print(f"{array}")
tensor = torch.from_numpy(array)
print(f"{tensor}")

[1 2 3 4 5 6 7]
tensor([1, 2, 3, 4, 5, 6, 7])


In [51]:
# Repoducibility(used with a seed to reduce randomness)
random_tensor_A= torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[8.0288e-01, 1.3142e-01, 7.7205e-01, 2.2320e-02],
        [3.1483e-04, 7.7056e-01, 2.5423e-01, 6.8048e-01],
        [8.9284e-01, 5.3588e-02, 8.2372e-01, 7.3116e-01]])
tensor([[0.0811, 0.9183, 0.1667, 0.0315],
        [0.4209, 0.5275, 0.0305, 0.4398],
        [0.8706, 0.6543, 0.0680, 0.7499]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [52]:
random_seed =82
# rand seed
torch.manual_seed(random_seed)
random_tensor_C= torch.rand(3,4)
# rand seed again
torch.manual_seed(random_seed)
random_tensor_D= torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D )

tensor([[0.4578, 0.5315, 0.6431, 0.1698],
        [0.7182, 0.8449, 0.1788, 0.5927],
        [0.3971, 0.8382, 0.5383, 0.2787]])
tensor([[0.4578, 0.5315, 0.6431, 0.1698],
        [0.7182, 0.8449, 0.1788, 0.5927],
        [0.3971, 0.8382, 0.5383, 0.2787]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
