<a href="https://colab.research.google.com/github/kaiju-no-9/Pytorch-Notes-/blob/main/fund_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensors

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.9.0+cpu


In [ ]:
#scalr
scalar = torch.tensor(7)
scalar


tensor(7)

In [ ]:
vector = torch.tensor([7,7])
vector
print(vector.ndim)
print(vector.shape)

1
torch.Size([2])


In [ ]:
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX
print(MATRIX.ndim)
print(MATRIX.shape)

2
torch.Size([2, 2])


In [ ]:
# Tesors
TENSORS= torch.tensor([[[1,2,3],[2,3,4],[4,5,6]]])
TENSORS
print(TENSORS.ndim)
print(TENSORS.shape)
print(TENSORS[0,0,0])

3
torch.Size([1, 3, 3])
tensor(1)


In [ ]:
# randrom
# they are imp bracuse a neutra network starts with a
# random set of numbers which the models work on to update
random_tansor = torch.rand(3,4)
random_tansor

tensor([[0.3324, 0.6989, 0.9667, 0.2474],
        [0.7787, 0.5311, 0.9450, 0.6848],
        [0.4138, 0.6006, 0.5787, 0.1377]])

In [ ]:
random_imagesize= torch.rand(size=(3,224,224))
random_imagesize.ndim , random_imagesize.shape

(3, torch.Size([3, 224, 224]))

In [ ]:
# tesors witj 0 and 1
zeros = torch.zeros(size=(3,4))
zeros
# once tenssor
once = torch.ones(size=(3,4))
once

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
#range(use arange ) start, stop , step
one_to_ten=torch.arange(1,11)


In [ ]:
#creating tensor likes
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#float tensor datatype
float_32_tensor= torch.tensor([2.0,1.0, 9.0] , dtype=None , device=None , requires_grad=False)
float_32_tensor
#

tensor([2., 1., 9.])

the issue you are goingto face ->(Not always)
1. tesor not right datatype
2. Tesor not right  shape
3. Tesor not on right device


In [ ]:
int_32_tensor =torch.tensor([3,6,9] , dtype= torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
#Tensor manuplation(add, sub ,multi(elemnet) , div , matrix mutiplication )
tensor = torch.tensor([1,2,3])
tensor+10
tensor*10


tensor([10, 20, 30])

In [ ]:
# Matrix multiplication
print(tensor * tensor )

tensor([1, 4, 9])


In [2]:
# for matrix multiplication
torch.matmul(tensor , tensor )

sample_data/


roles required for matrix multiplication

1.the inner dommition must match .
2. the resulting matrix has the shape of the outer dimmition

In [5]:
# tensor shape issue !!
torch_A = torch.tensor([[1,2],
                       [2,3],
                      [3,4]])
torch_B= torch.tensor([[3,4], [4,5],[6,7]])


In [10]:
# Swtiching and transpose
print(f"origal_shape : {torch_A.shape} , {torch_B.shape}")
print("......")
print(f"new  matrix : {torch_A.shape} , {torch_B.T.shape}")
print("......")
print(torch.matmul(torch_A , torch_B.T))



origal_shape : torch.Size([3, 2]) , torch.Size([3, 2])
......
new  matrix : torch.Size([3, 2]) , torch.Size([2, 3])
......
tensor([[11, 14, 20],
        [18, 23, 33],
        [25, 32, 46]])
